#app: /Users/example/Library/Developer/Xcode/DerivedData/CoreDataBooks-ebscrjfhxtkvdfcmtuwluoitjjwo/Build/Products/Debug-iphonesimulator/CoreDataBooks.app

devices:
  Simulator:
    screen: retina_ios6
    default: true
    simulator: iPhone (Retina 3.5-inch)

  iPhone 4:
    UDID  : hey88thisdisc6efjust22097ac0sampled2udid
    screen: retina_ios5
